deploy_development:
  stage: deploy
  image: lwolf/kubectl_deployer:1.18.3
  script:
    - /bin/sh deploy.sh ${CI_BUILD_REF_NAME}_${CI_BUILD_REF}
  environment: development

deploy_staging:
  stage: deploy
  image: lwolf/kubectl_deployer:1.18.3
  script:
    - /bin/sh deploy.sh ${CI_BUILD_REF_NAME}_${CI_BUILD_REF}
  environment: staging
  when: manual

deploy_production:
  stage: deploy
  image: lwolf/kubectl_deployer:1.18.3
  script:
    - /bin/sh deploy.sh ${CI_BUILD_REF_NAME}_${CI_BUILD_REF}
  environment: production
  when: manual